# Generated by Django 5.2.5 on 2025-08-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
